services:
  web:
    build:
      context: .
      dockerfile: ./docker/common/Dockerfile
      target: nginx-production
    restart: unless-stopped
    networks:
      - laravel-production
    depends_on:
      php-fpm:
        condition: service_healthy

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/common/Dockerfile
      target: php-fpm-production
    restart: unless-stopped
    networks:
      - laravel-production
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  laravel-production:
