version: "3.9"
services:
    cron:
        image: crazymax/swarm-cronjob:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            LOG_LEVEL: info
        deploy:
            placement:
                constraints: [ node.role == manager ]

    frontend:
        image: ${REGISTRY}/finsly-frontend:${IMAGE_TAG}
        environment:
            REACT_APP_AUTH_URL: https://api.finsly.ru
        networks:
            - traefik-public
            - default
        deploy:
            labels:
                - traefik.enable=true
                - traefik.docker.network=traefik-public
                - traefik.http.routers.frontend.rule=Host(`finsly.ru`) || Host(`finsly.ru`)
                - traefik.http.services.frontend.loadBalancer.server.port=80
                - traefik.http.middlewares.frontend-redirect.redirectRegex.regex=^(https?://)finsly.ru/(.*)$$
                - traefik.http.middlewares.frontend-redirect.redirectRegex.replacement=$${1}finsly.ru/$${2}
                - traefik.http.middlewares.frontend-redirect.redirectRegex.permanent=true
                - traefik.http.routers.frontend.middlewares=frontend-redirect,secure-headers
                - traefik.http.routers.frontend.entryPoints=https
                - traefik.http.routers.frontend.tls=true
                - traefik.http.routers.frontend.tls.certResolver=letsEncrypt
            mode: replicated
            replicas: 2
            update_config:
                parallelism: 1
                delay: 10s

    api:
        image: ${REGISTRY}/finsly-api:${IMAGE_TAG}
        networks:
            - traefik-public
            - default
        deploy:
            labels:
                - traefik.enable=true
                - traefik.docker.network=traefik-public
                - traefik.http.routers.api.rule=Host(`api.finsly.ru`)
                - traefik.http.services.api.loadBalancer.server.port=80
                - traefik.http.routers.api.middlewares=secure-headers
                - traefik.http.routers.api.entryPoints=https
                - traefik.http.routers.api.tls=true
                - traefik.http.routers.api.tls.certResolver=letsEncrypt
            mode: replicated
            replicas: 2
            update_config:
                parallelism: 1
                delay: 5s

    api-php-fpm:
        image: ${REGISTRY}/finsly-api-php-fpm:${IMAGE_TAG}
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_USER: ${DB_USER}
            DB_PASSWORD_FILE: /run/secrets/api_db_password
            DB_NAME: ${DB_NAME}
            CACHE_HOST: ${CACHE_HOST}
            CACHE_PORT: ${CACHE_PORT}
            CACHE_USER: ${CACHE_USER}
            CACHE_PASSWORD_FILE: /run/secrets/cache_password
            MAILER_HOST: ${API_MAILER_HOST}
            MAILER_PORT: ${API_MAILER_PORT}
            MAILER_USERNAME: ${API_MAILER_USERNAME}
            MAILER_PASSWORD_FILE: /run/secrets/api_mailer_password
            MAILER_FROM_EMAIL: ${API_MAILER_FROM_EMAIL}
            FRONTEND_URL: https://finsly.ru
            SENTRY_DSN_FILE: /run/secrets/sentry_dsn
            JWT_ENCRYPTION_KEY_FILE: /run/secrets/jwt_encryption_key
            JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
            JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
            OAUTH_CALLBACK_URL: https://api.finsly.ru
            OAUTH_YANDEX_AUTH_URL: https://oauth.yandex.ru
            OAUTH_YANDEX_TOKEN_URL: https://oauth.yandex.ru
            OAUTH_YANDEX_API_URL: https://login.yandex.ru
            OAUTH_YANDEX_CLIENT_ID: ${OAUTH_YANDEX_CLIENT_ID}
            OAUTH_YANDEX_CLIENT_SECRET_FILE: /run/secrets/oauth_yandex_client_secret
            OAUTH_MAILRU_AUTH_URL: https://oauth.mail.ru
            OAUTH_MAILRU_TOKEN_URL: https://oauth.mail.ru
            OAUTH_MAILRU_API_URL: https://oauth.mail.ru
            OAUTH_MAILRU_CLIENT_ID: ${OAUTH_MAILRU_CLIENT_ID}
            OAUTH_MAILRU_CLIENT_SECRET_FILE: /run/secrets/oauth_mailru_client_secret
            EXCHANGE_RATE_API_URL: ${EXCHANGE_RATE_API_URL}
            EXCHANGE_RATE_API_KEY_FILE: /run/secrets/exchange_rate_api_key
        secrets:
            - api_db_password
            - api_mailer_password
            - sentry_dsn
            - jwt_encryption_key
            - jwt_public_key
            - jwt_private_key
            - oauth_yandex_client_secret
            - oauth_mailru_client_secret
            - exchange_rate_api_key
            - cache_password
        deploy:
            mode: replicated
            replicas: 2
            update_config:
                parallelism: 1
                delay: 5s

    api-migration:
        image: ${REGISTRY}/finsly-api-php-cli:${IMAGE_TAG}
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_USER: ${DB_USER}
            DB_PASSWORD_FILE: /run/secrets/api_db_password
            DB_NAME: ${DB_NAME}
            CACHE_HOST: ${CACHE_HOST}
            CACHE_PORT: ${CACHE_PORT}
            CACHE_USER: ${CACHE_USER}
            CACHE_PASSWORD_FILE: /run/secrets/cache_password
            MAILER_HOST: ${API_MAILER_HOST}
            MAILER_PORT: ${API_MAILER_PORT}
            MAILER_USERNAME: ${API_MAILER_USERNAME}
            MAILER_PASSWORD_FILE: /run/secrets/api_mailer_password
            MAILER_FROM_EMAIL: ${API_MAILER_FROM_EMAIL}
            FRONTEND_URL: https://finsly.ru
            SENTRY_DSN_FILE: /run/secrets/sentry_dsn
            JWT_ENCRYPTION_KEY_FILE: /run/secrets/jwt_encryption_key
            JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
            JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
            OAUTH_CALLBACK_URL: https://api.finsly.ru
            OAUTH_YANDEX_AUTH_URL: https://oauth.yandex.ru
            OAUTH_YANDEX_TOKEN_URL: https://oauth.yandex.ru
            OAUTH_YANDEX_API_URL: https://login.yandex.ru
            OAUTH_YANDEX_CLIENT_ID: ${OAUTH_YANDEX_CLIENT_ID}
            OAUTH_YANDEX_CLIENT_SECRET_FILE: /run/secrets/oauth_yandex_client_secret
            OAUTH_MAILRU_AUTH_URL: https://oauth.mail.ru
            OAUTH_MAILRU_TOKEN_URL: https://oauth.mail.ru
            OAUTH_MAILRU_API_URL: https://oauth.mail.ru
            OAUTH_MAILRU_CLIENT_ID: ${OAUTH_MAILRU_CLIENT_ID}
            OAUTH_MAILRU_CLIENT_SECRET_FILE: /run/secrets/oauth_mailru_client_secret
        secrets:
            - api_db_password
            - api_mailer_password
            - sentry_dsn
            - jwt_encryption_key
            - jwt_public_key
            - jwt_private_key
            - oauth_yandex_client_secret
            - oauth_mailru_client_secret
            - cache_password
        command: sh -c 'php bin/app.php migrations:migrate --no-interaction'
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 5
                window: 120s

    api-oauth-clear-expired:
        image: ${REGISTRY}/finsly-api-php-cli:${IMAGE_TAG}
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_USER: ${DB_USER}
            DB_PASSWORD_FILE: /run/secrets/api_db_password
            DB_NAME: ${DB_NAME}
            CACHE_HOST: ${CACHE_HOST}
            CACHE_PORT: ${CACHE_PORT}
            CACHE_USER: ${CACHE_USER}
            CACHE_PASSWORD_FILE: /run/secrets/cache_password
            MAILER_HOST: ${API_MAILER_HOST}
            MAILER_PORT: ${API_MAILER_PORT}
            MAILER_USERNAME: ${API_MAILER_USERNAME}
            MAILER_PASSWORD_FILE: /run/secrets/api_mailer_password
            MAILER_FROM_EMAIL: ${API_MAILER_FROM_EMAIL}
            FRONTEND_URL: https://finsly.ru
            SENTRY_DSN_FILE: /run/secrets/sentry_dsn
            JWT_ENCRYPTION_KEY_FILE: /run/secrets/jwt_encryption_key
            JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
            JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
            OAUTH_CALLBACK_URL: https://api.finsly.ru
            OAUTH_YANDEX_AUTH_URL: https://oauth.yandex.ru
            OAUTH_YANDEX_TOKEN_URL: https://oauth.yandex.ru
            OAUTH_YANDEX_API_URL: https://login.yandex.ru
            OAUTH_YANDEX_CLIENT_ID: ${OAUTH_YANDEX_CLIENT_ID}
            OAUTH_YANDEX_CLIENT_SECRET_FILE: /run/secrets/oauth_yandex_client_secret
            OAUTH_MAILRU_AUTH_URL: https://oauth.mail.ru
            OAUTH_MAILRU_TOKEN_URL: https://oauth.mail.ru
            OAUTH_MAILRU_API_URL: https://oauth.mail.ru
            OAUTH_MAILRU_CLIENT_ID: ${OAUTH_MAILRU_CLIENT_ID}
            OAUTH_MAILRU_CLIENT_SECRET_FILE: /run/secrets/oauth_mailru_client_secret
        secrets:
            - api_db_password
            - api_mailer_password
            - sentry_dsn
            - jwt_encryption_key
            - jwt_public_key
            - jwt_private_key
            - oauth_yandex_client_secret
            - oauth_mailru_client_secret
            - cache_password
        command: sh -c 'php bin/app.php oauth:clear-expired'
        deploy:
            labels:
                - swarm.cronjob.enable=true
                - swarm.cronjob.schedule=0 * * * *
                - swarm.cronjob.skip-running=true
            replicas: 0
            restart_policy:
                condition: none

secrets:
    cache_password:
        file: ./secrets/cache_password
    api_db_password:
        file: ./secrets/api_db_password
    api_mailer_password:
        file: ./secrets/api_mailer_password
    sentry_dsn:
        file: ./secrets/sentry_dsn
    jwt_encryption_key:
        file: ./secrets/jwt_encryption_key
    jwt_public_key:
        file: ./secrets/jwt_public_key
    jwt_private_key:
        file: ./secrets/jwt_private_key
    oauth_yandex_client_secret:
        file: ./secrets/oauth_yandex_client_secret
    oauth_mailru_client_secret:
        file: ./secrets/oauth_mailru_client_secret
    exchange_rate_api_key:
        file: ./secrets/exchange_rate_api_key

networks:
    traefik-public:
        external: true
