services:
    traefik:
        image: traefik:2.11
        command:
            --providers.docker=true
            --providers.docker.exposedByDefault=false
            --entryPoints.http.address=:80
        ports:
            - "80:80"
        networks:
            - traefik-public
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public

    frontend:
        build:
            context: frontend/docker/development/nginx
        networks:
            - traefik-public
            - default
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.frontend.rule=Host(`localhost`) || Host(`www.localhost`)
            - traefik.http.routers.frontend.entryPoints=http
            - traefik.http.services.frontend.loadBalancer.server.port=80
            - traefik.http.middlewares.frontend-redirect.redirectRegex.regex=^(https?://)www.localhost/(.*)$$
            - traefik.http.middlewares.frontend-redirect.redirectRegex.replacement=$${1}localhost/$${2}
            - traefik.http.middlewares.frontend-redirect.redirectRegex.permanent=true
            - traefik.http.routers.frontend.middlewares=frontend-redirect

    frontend-node:
        build:
            context: frontend/docker/development/node
        environment:
            WDS_SOCKET_PORT: 0
            REACT_APP_AUTH_URL: http://api.localhost
        volumes:
            - ./frontend:/app
        command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && yarn start"
        tty: true

    frontend-node-cli:
        build:
            context: frontend/docker/development/node
        volumes:
            - ./frontend:/app

    api:
        build:
            context: api/docker
            dockerfile: development/nginx/Dockerfile
        volumes:
            - ./api:/app
        networks:
            - traefik-public
            - default
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.api.rule=Host(`api.localhost`)
            - traefik.http.routers.api.entryPoints=http
            - traefik.http.services.api.loadBalancer.server.port=80

    api-php-fpm:
        build:
            context: api/docker
            dockerfile: development/php-fpm/Dockerfile
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            PHP_IDE_CONFIG: serverName=API
            DB_HOST: api-postgres
            DB_PORT: 5432
            DB_USER: app
            DB_PASSWORD_FILE: /run/secrets/api_db_password
            DB_NAME: app
            CACHE_HOST: api-valkey
            CACHE_PORT: 6379
            CACHE_USER: default
            CACHE_PASSWORD_FILE: /run/secrets/cache_password
            MAILER_HOST: mailer
            MAILER_PORT: 1025
            MAILER_USERNAME: app
            MAILER_PASSWORD_FILE: /run/secrets/api_mailer_password
            MAILER_FROM_EMAIL: mail@app.test
            FRONTEND_URL: http://localhost
            SENTRY_DSN_FILE: /run/secrets/sentry_dsn
            JWT_ENCRYPTION_KEY_FILE: /run/secrets/jwt_encryption_key
            JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
            JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
            OAUTH_CALLBACK_URL: http://api.localhost
            OAUTH_YANDEX_AUTH_URL: http://wiremock.localhost/oauth.yandex.ru
            OAUTH_YANDEX_TOKEN_URL: http://wiremock/oauth.yandex.ru
            OAUTH_YANDEX_API_URL: http://wiremock/login.yandex.ru
            OAUTH_YANDEX_CLIENT_ID: app
            OAUTH_YANDEX_CLIENT_SECRET_FILE: /run/secrets/oauth_yandex_client_secret
            OAUTH_MAILRU_AUTH_URL: http://wiremock.localhost/oauth.mail.ru
            OAUTH_MAILRU_TOKEN_URL: http://wiremock/oauth.mail.ru
            OAUTH_MAILRU_API_URL: http://wiremock/oauth.mail.ru
            OAUTH_MAILRU_CLIENT_ID: app
            OAUTH_MAILRU_CLIENT_SECRET_FILE: /run/secrets/oauth_mailru_client_secret
            EXCHANGE_RATE_API_URL: http://wiremock/v6.exchangerate-api.com/v6
            EXCHANGE_RATE_API_KEY_FILE: /run/secrets/exchange_rate_api_key
        volumes:
            - ./api:/app
        secrets:
            - api_db_password
            - api_mailer_password
            - sentry_dsn
            - jwt_encryption_key
            - jwt_public_key
            - jwt_private_key
            - oauth_yandex_client_secret
            - oauth_mailru_client_secret
            - exchange_rate_api_key
            - cache_password

    api-php-cli:
        build:
            context: api/docker
            dockerfile: development/php-cli/Dockerfile
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            DB_HOST: api-postgres
            DB_PORT: 5432
            DB_USER: app
            DB_PASSWORD_FILE: /run/secrets/api_db_password
            DB_NAME: app
            CACHE_HOST: api-valkey
            CACHE_PORT: 6379
            CACHE_USER: default
            MAILER_HOST: mailer
            MAILER_PORT: 1025
            MAILER_USERNAME: app
            MAILER_PASSWORD_FILE: /run/secrets/api_mailer_password
            MAILER_FROM_EMAIL: mail@app.test
            FRONTEND_URL: http://localhost
            SENTRY_DSN_FILE: /run/secrets/sentry_dsn
            JWT_ENCRYPTION_KEY_FILE: /run/secrets/jwt_encryption_key
            JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
            JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
            OAUTH_CALLBACK_URL: http://api.localhost
            OAUTH_YANDEX_AUTH_URL: http://wiremock.localhost/oauth.yandex.ru
            OAUTH_YANDEX_TOKEN_URL: http://wiremock/oauth.yandex.ru
            OAUTH_YANDEX_API_URL: http://wiremock/login.yandex.ru
            OAUTH_YANDEX_CLIENT_ID: app
            OAUTH_YANDEX_CLIENT_SECRET_FILE: /run/secrets/oauth_yandex_client_secret
            OAUTH_MAILRU_AUTH_URL: http://wiremock.localhost/oauth.mail.ru
            OAUTH_MAILRU_TOKEN_URL: http://wiremock/oauth.mail.ru
            OAUTH_MAILRU_API_URL: http://wiremock/oauth.mail.ru
            OAUTH_MAILRU_CLIENT_ID: app
            OAUTH_MAILRU_CLIENT_SECRET_FILE: /run/secrets/oauth_mailru_client_secret
        volumes:
            - ./api:/app
        secrets:
            - api_db_password
            - api_mailer_password
            - sentry_dsn
            - jwt_encryption_key
            - jwt_public_key
            - jwt_private_key
            - oauth_yandex_client_secret
            - oauth_mailru_client_secret

    api-postgres:
        image: postgres:13.3-alpine3.14
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD_FILE: /run/secrets/api_db_password
            POSTGRES_DB: app
        secrets:
            - api_db_password
        volumes:
            - api-postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    mailer:
        image: mailhog/mailhog
        networks:
            - traefik-public
            - default
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.mailer.rule=Host(`mailer.localhost`)
            - traefik.http.routers.mailer.entryPoints=http
            - traefik.http.services.mailer.loadBalancer.server.port=8025

    wiremock:
        image: wiremock/wiremock:3x-alpine
        networks:
            - traefik-public
            - default
        volumes:
            - ./wiremock:/home/wiremock
        healthcheck:
            test: wget --no-verbose --tries=1 --spider http://localhost/__admin/health || exit 1
        command:
            - '--port=80'
            - '--global-response-templating'
            - '--verbose'
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.wiremock.rule=Host(`wiremock.localhost`)
            - traefik.http.services.wiremock.loadBalancer.server.port=80
            - traefik.http.routers.wiremock.entryPoints=http

    cucumber-node-cli:
        build:
            context: cucumber/docker/development/node
        volumes:
            - ./cucumber:/app
        network_mode: service:traefik

    api-valkey:
        image: valkey/valkey:8.0.2
        ports:
            - "6379:6379"

secrets:
    api_db_password:
        file: ./docker/development/secrets/api_db_password
    api_mailer_password:
        file: ./docker/development/secrets/api_mailer_password
    sentry_dsn:
        file: ./docker/development/secrets/sentry_dsn
    jwt_encryption_key:
        file: ./docker/development/secrets/jwt_encryption_key
    jwt_public_key:
        file: ./docker/development/secrets/jwt_public_key
    jwt_private_key:
        file: ./docker/development/secrets/jwt_private_key
    oauth_yandex_client_secret:
        file: ./docker/development/secrets/oauth_yandex_client_secret
    oauth_mailru_client_secret:
        file: ./docker/development/secrets/oauth_mailru_client_secret
    exchange_rate_api_key:
        file: ./docker/development/secrets/exchange_rate_api_key
    cache_password:
        file: ./docker/development/secrets/cache_password

volumes:
    api-postgres:

networks:
    traefik-public:
        name: traefik-public
